services:
  - type: web
    name: social-media-portfolio
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "portfolio.settings"
      - key: PYTHONUNBUFFERED
        value: "1"
